// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Voluta.Data;

#nullable disable

namespace Voluta.Migrations
{
    [DbContext(typeof(VolutaDbContext))]
    [Migration("20250531212253_AdicionaInsertDeUsuarios")]
    partial class AdicionaInsertDeUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OngUsuario", b =>
                {
                    b.Property<int>("OngsVoluntarioId")
                        .HasColumnType("int");

                    b.Property<int>("VoluntariosId")
                        .HasColumnType("int");

                    b.HasKey("OngsVoluntarioId", "VoluntariosId");

                    b.HasIndex("VoluntariosId");

                    b.ToTable("UsuariosOngs", (string)null);
                });

            modelBuilder.Entity("Voluta.Models.Ong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreasAtuacaoJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nome");

                    b.ToTable("Ongs");
                });

            modelBuilder.Entity("Voluta.Models.SolicitacaoVoluntariado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAprovacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OngId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OngId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("Status", "DataSolicitacao");

                    b.ToTable("SolicitacoesVoluntariado");
                });

            modelBuilder.Entity("Voluta.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreasInteresseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Disponivel");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nome");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreasInteresseJson = "[0]",
                            DataCadastro = new DateTime(2025, 5, 31, 18, 22, 52, 587, DateTimeKind.Local).AddTicks(1451),
                            Disponivel = false,
                            Email = "usuario@voluta.com",
                            Nome = "Usuario",
                            Role = 1,
                            SenhaHash = "$2a$11$sM2r6Ennv1KTPT5sfgD5a.cB0H3iZqLA502MaTs02jZYfxhwy7ZaW",
                            Telefone = "(11) 99999-9999"
                        },
                        new
                        {
                            Id = 2,
                            AreasInteresseJson = "[0]",
                            DataCadastro = new DateTime(2025, 5, 31, 18, 22, 52, 685, DateTimeKind.Local).AddTicks(2324),
                            Disponivel = false,
                            Email = "admin@voluta.com",
                            Nome = "Admin",
                            Role = 0,
                            SenhaHash = "$2a$11$4tkN3MP8BY1da1E5rW3HNeBVLe1kg65X9.usgpVVw0VCEGRktxgym",
                            Telefone = "(11) 99999-9999"
                        },
                        new
                        {
                            Id = 3,
                            AreasInteresseJson = "[0]",
                            DataCadastro = new DateTime(2025, 5, 31, 18, 22, 52, 783, DateTimeKind.Local).AddTicks(7845),
                            Disponivel = false,
                            Email = "representante@ong.com",
                            Nome = "Representante ONG",
                            Role = 2,
                            SenhaHash = "$2a$11$bwCCxOrJPRuHzamsAGhAOuZGt8pAHP.zFeaJz2ORTEEGOw3gtfb6S",
                            Telefone = "(11) 88888-8888"
                        });
                });

            modelBuilder.Entity("OngUsuario", b =>
                {
                    b.HasOne("Voluta.Models.Ong", null)
                        .WithMany()
                        .HasForeignKey("OngsVoluntarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Voluta.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("VoluntariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Voluta.Models.SolicitacaoVoluntariado", b =>
                {
                    b.HasOne("Voluta.Models.Ong", "Ong")
                        .WithMany("SolicitacoesVoluntariado")
                        .HasForeignKey("OngId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Voluta.Models.Usuario", "Usuario")
                        .WithMany("SolicitacoesVoluntariado")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ong");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Voluta.Models.Ong", b =>
                {
                    b.Navigation("SolicitacoesVoluntariado");
                });

            modelBuilder.Entity("Voluta.Models.Usuario", b =>
                {
                    b.Navigation("SolicitacoesVoluntariado");
                });
#pragma warning restore 612, 618
        }
    }
}
